openapi: 3.0.0
info:
  title: SmolDesk API
  version: "0.1.0"
paths:
  /ping:
    get:
      summary: Ping
      responses:
        '200':
          description: Pong
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: pong
