import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'docs/architecture',
    {
      type: 'category',
      label: '📖 Einführung',
      items: [
        'usage/viewer',
        'usage/clipboard',
        'usage/files',
        'usage/monitors',
        'features/security',
      ],
    },
    {
      type: 'category',
      label: '📦 Komponenten',
      items: [{type: 'autogenerated', dirName: 'components'}],
    },
    {
      type: 'category',
      label: '📱 Mobile App',
      items: [
        'development/setup-android',
        'development/setup-ios',
      ],
    },
    {
      type: 'category',
      label: '🧑‍💻 Entwicklung',
      items: [{type: 'autogenerated', dirName: 'development'}],
    },
    {
      type: 'category',
      label: '🧪 Testing',
      items: [{type: 'autogenerated', dirName: 'testing'}],
    },
    {
      type: 'category',
      label: '📜 API',
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
    {
      type: 'category',
      label: 'Demo & Playground',
      items: [
        'docs/demo/live-demo',
        'docs/demo/api-playground',
      ],
    },
    {
      type: 'category',
      label: '🚀 Öffentliche Releases',
      items: [{type: 'autogenerated', dirName: 'release'}],
    },
  ],
};

export default sidebars;
