import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'docs/architecture',
    { type: 'autogenerated', dirName: 'development' },
    { type: 'autogenerated', dirName: 'components' },
    { type: 'autogenerated', dirName: 'api' },
    { type: 'autogenerated', dirName: 'testing' },
    { type: 'autogenerated', dirName: 'usage' },
    { type: 'autogenerated', dirName: 'release' },
    { type: 'autogenerated', dirName: 'agents' },
    {
      type: 'category',
      label: 'Setup',
      items: [
        'development/setup-android',
        'development/setup-ios',
      ],
    },
    {
      type: 'category',
      label: 'Archive',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'archive' }],
    },
  ],
};

export default sidebars;
