name: Deploy Storybook

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build:storybook
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
      - name: Upload fallback artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-preview
          path: storybook-static
      - name: comment artifact link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❗ GitHub Pages ist derzeit nicht erreichbar. Lade das Vorschau-Artefakt herunter: [📦 Storybook Preview (artifact)](https://github.com/${context.repo.owner}/${context.repo.repo}/actions)'
            })
