name: Deploy Storybook

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install and build
        run: |
          npm ci
          VITE_COMMIT_SHA=$(git rev-parse HEAD) VITE_VERSION=$(jq -r '.version' package.json) npm run build:storybook
      - name: verify build output
        run: |
          test -f storybook-static/index.html
          touch storybook-static/.nojekyll
          cp storybook-static/index.html storybook-static/404.html # reuse index for 404 page
      - name: Force-push to gh-pages
        run: |
          git config --global user.name "codex-ci"
          git config --global user.email "ci@codex.local"
          git checkout --orphan gh-pages
          git reset
          cp -r storybook-static/* .
          git add .
          git commit -m "chore: publish storybook"
          git push --force origin gh-pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages
          cname: ''
      - name: Upload fallback artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-preview
          path: storybook-static
      - name: comment artifact link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❗ GitHub Pages ist derzeit nicht erreichbar. Lade das Vorschau-Artefakt herunter: [📦 Storybook Preview (artifact)](https://github.com/${context.repo.owner}/${context.repo.repo}/actions)'
            })
