name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Install dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libssl-dev \
          ffmpeg \
          wl-clipboard \
          xclip \
          ydotool \
          xdotool
    
    - name: Install cross-compilation tools (ARM64)
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
    
    - name: Install frontend dependencies
      run: npm install
    
    - name: Build Tauri app
      run: npm run tauri build -- --target ${{ matrix.target }}
    
    - name: Create DEB package
      run: |
        ./scripts/package-deb.sh ${{ matrix.target }}
    
    - name: Create RPM package
      run: |
        ./scripts/package-rpm.sh ${{ matrix.target }}
    
    - name: Create AppImage
      if: matrix.target == 'x86_64-unknown-linux-gnu'
      run: |
        ./scripts/package-appimage.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SmolDesk-${{ matrix.target }}
        path: |
          target/release/bundle/deb/*.deb
          target/release/bundle/rpm/*.rpm
          target/release/bundle/appimage/*.AppImage

  build-flatpak:
    runs-on: ubuntu-22.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Flatpak
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: SmolDesk.flatpak
        manifest-path: packaging/flatpak/com.smoldesk.SmolDesk.yml
    
    - name: Upload Flatpak
      uses: actions/upload-artifact@v4
      with:
        name: SmolDesk-Flatpak
        path: SmolDesk.flatpak

  release:
    needs: [build-linux, build-flatpak]
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          SmolDesk-x86_64-unknown-linux-gnu/*.deb
          SmolDesk-x86_64-unknown-linux-gnu/*.rpm  
          SmolDesk-x86_64-unknown-linux-gnu/*.AppImage
          SmolDesk-aarch64-unknown-linux-gnu/*.deb
          SmolDesk-aarch64-unknown-linux-gnu/*.rpm
          SmolDesk-Flatpak/*.flatpak
        body: |
          ## SmolDesk Release ${{ github.ref_name }}
          
          ### Installation Instructions
          
          **Debian/Ubuntu (.deb):**
          ```bash
          wget https://github.com/SmolDesk/SmolDesk/releases/download/${{ github.ref_name }}/smoldesk_1.0.0_amd64.deb
          sudo apt install ./smoldesk_1.0.0_amd64.deb
          ```
          
          **Fedora/RHEL (.rpm):**
          ```bash
          wget https://github.com/SmolDesk/SmolDesk/releases/download/${{ github.ref_name }}/smoldesk-1.0.0-1.x86_64.rpm
          sudo dnf install ./smoldesk-1.0.0-1.x86_64.rpm
          ```
          
          **AppImage (Universal):**
          ```bash
          wget https://github.com/SmolDesk/SmolDesk/releases/download/${{ github.ref_name }}/SmolDesk-1.0.0-x86_64.AppImage
          chmod +x SmolDesk-1.0.0-x86_64.AppImage
          ./SmolDesk-1.0.0-x86_64.AppImage
          ```
          
          **Flatpak:**
          ```bash
          flatpak install SmolDesk.flatpak
          ```
        draft: false
        prerelease: false
